baseURL = "https://jujinkim.com"
title = "JujinKim's Blog"
DefaultContentLanguage = "en"
theme = "hugo-PaperMod"
hasCJKLanguage = true
copyright = "Jujin Kim (Dangumju)"
googleAnalytics = "UA-54002449-3"
enableRobotsTXT = true

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About me"
        url = "../me"
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/post"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "/archives"

[languages]
    [languages.ko]
        title = "김주진 블로그"
        languageName = "한국어"
        weight = 1
    [languages.en]
        title = "Jujin Kim's blog"
        languageName = "English"
        weight = 2

[params]
    env = "production"
    title = "JujinKim's Blog"
    description = "JujinKim's engineering blog"
    autor = "Jujin Kim"
    defaultTheme = "auto"
    layout = "archives"
    ShowShareButtons = true
    ShowReadingTime = true
    ShowToc = true
    TocOpen = true
    comments = true
    [params.homeInfoParams]
        Title = "Hi there"
        Content = "Thanks for visiting my blog. Have a nice day :)"
    [params.navigation]
        help = "Help"
        
[minify]
    disableXML = true
    minifyOutput = true

[outputs]
    home = ["HTML", "RSS"]

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"